---
title: Build a robot buggy
hero_image: images/banner.png
description: Build and control a robot buggy
original_url:
theme: violet
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-1, community-0
interests: robotics, big-project
technologies: electronic-components, python, raspberry-pi
hardware: electronic-components, raspberry-pi
software: python
site_areas: projects
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Set up your motors
- title: Left, right, forward, backward
  completion:
  - engaged
- title: Assemble your robot
  completion:
  - internal
- title: 'Challenge: program your robot'
